server:
  port: 8761

spring:
  application:
    name: eureka-server

# O próprio servidor não se registra nem busca o registro.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
